export { SecretaryStudentsPage } from './StudentsPage'
export { SecretaryEnrollmentsPage } from './EnrollmentsPage'
export { SecretaryPaymentsPage } from './PaymentsPage'
export { SecretaryDocumentsPage } from './DocumentsPage'
export { SecretaryContactsPage } from './ContactsPage'
export { SecretaryAppointmentsPage } from './AppointmentsPage'
export { SecretaryPrintingPage } from './PrintingPage'
export { SecretarySettingsPage } from './SettingsPage'