'use client'

import { useState } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import * as z from 'zod'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { studentService } from '@/services/student.service'
import { toast } from 'sonner'

const formSchema = z.object({
  nom: z.string().min(2, 'Le nom doit contenir au moins 2 caractères'),
  prenom: z.string().min(2, 'Le prénom doit contenir au moins 2 caractères'),
  dateNaissance: z.string().refine((date) => new Date(date).toString() !== 'Invalid Date', {
    message: 'Date invalide',
  }),
  lieuNaissance: z.string().optional(),
  sexe: z.enum(['M', 'F']),
  matricule: z.string().optional(), // Often generated by backend, but can be manual
  classeId: z.string().optional(), // For enrollment
})

interface StudentFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSuccess: () => void
}

export function StudentForm({ open, onOpenChange, onSuccess }: StudentFormProps) {
  const [isLoading, setIsLoading] = useState(false)

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      nom: '',
      prenom: '',
      dateNaissance: '',
      lieuNaissance: '',
      sexe: 'M',
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    try {
      setIsLoading(true)
      // Note: The API likely expects a specific format.
      // Adjusting to match CreateEleveRequest which might need numerical IDs or specific fields.
      // Based on previous EleveDto/CreateEleveRequest, we map accordingly.

      await studentService.create({
        nom: values.nom,
        prenom: values.prenom,
        dateNaissance: values.dateNaissance, // React hook form 'date' input returns yyyy-mm-dd string usually, or we can slice it if it's a date object? The schema says string. If input type="date", value is yyyy-mm-dd. So we can just pass it directly if we trust it, or specifically value.dateNaissance.split('T')[0] if it was parsed. Zod schema says string. Input type="date". So it is "YYYY-MM-DD".
        lieuNaissance: values.lieuNaissance,
        sexe: values.sexe,
        // Other fields might need to be handled if added to CreateEleveRequest
      })

      toast.success('Élève créé avec succès')
      form.reset()
      onSuccess()
      onOpenChange(false)
    } catch (error) {
      console.error('Erreur création élève:', error)
      toast.error("Erreur lors de la création de l'élève")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Nouvel Élève</DialogTitle>
          <DialogDescription>Ajoutez un nouvel élève au système.</DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="nom"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Nom</FormLabel>
                  <FormControl>
                    <Input placeholder="Nom de l'élève" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="prenom"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Prénom</FormLabel>
                  <FormControl>
                    <Input placeholder="Prénom de l'élève" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="dateNaissance"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Date de naissance</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        max={
                          new Date(new Date().setFullYear(new Date().getFullYear() - 2))
                            .toISOString()
                            .split('T')[0]
                        }
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="sexe"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Sexe</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Sélectionner" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="M">Masculin</SelectItem>
                        <SelectItem value="F">Féminin</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                Annuler
              </Button>
              <Button
                type="submit"
                disabled={isLoading}
                className="bg-[#2302B3] hover:bg-[#1a0285]"
              >
                {isLoading ? 'Création...' : 'Créer'}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
