# ============================================
# Help Digi School - Frontend Next.js
# GitLab CI/CD - Pipeline Pre-Production
# ============================================

# ============================================
# Stage 1: Build - Génération du fichier .env
# ============================================
generate_env_preprod:
  stage: build
  image: alpine:3.20
  script:
    - |
      cat > .env.preprod << EOF
      # ============================================
      # APPLICATION
      # ============================================
      NODE_ENV=production
      NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME_PREPROD:-Help Digi School}
      NEXT_PUBLIC_APP_URL=${HOST_URL_PREPROD}
      NEXT_PUBLIC_APP_DESCRIPTION=Plateforme de gestion scolaire
      NEXT_PUBLIC_ENVIRONMENT=preprod

      # ============================================
      # API - MICROSERVICES
      # ============================================
      NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL_PREPROD}
      NEXT_PUBLIC_API_TIMEOUT=30000

      # ============================================
      # DOCKER
      # ============================================
      FRONTEND_PORT=${PORT_PREPROD:-32031}
      VERSION=${CI_COMMIT_SHORT_SHA}

      # ============================================
      # DATABASE (si nécessaire côté frontend)
      # ============================================
      # DB_HOST=${DB_HOST_PREPROD}
      # DB_PORT=${DB_PORT_PREPROD:-5432}
      # DB_USER=${DB_USER_PREPROD}
      # DB_PASSWORD=${DB_PASSWORD_PREPROD}
      # DB_NAME=${DB_NAME_PREPROD}

      # ============================================
      # REDIS (si nécessaire côté frontend)
      # ============================================
      # REDIS_HOST=${REDIS_HOST_PREPROD}
      # REDIS_PORT=${REDIS_PORT_PREPROD:-6379}

      # ============================================
      # SMTP (pour notifications)
      # ============================================
      # SMTP_HOST=${SMTP_HOST}
      # SMTP_PORT=${SMTP_PORT}
      # SMTP_USERNAME=${SMTP_USERNAME}
      # SMTP_PASSWORD=${SMTP_PASSWORD}

      # ============================================
      # AUTHENTIFICATION
      # ============================================
      NEXT_PUBLIC_SESSION_DURATION=3600

      # ============================================
      # FEATURES FLAGS
      # ============================================
      NEXT_PUBLIC_ENABLE_NOTIFICATIONS=true
      NEXT_PUBLIC_ENABLE_DARK_MODE=true
      NEXT_PUBLIC_ENABLE_ANALYTICS=false
      EOF
    - cat .env.preprod
  artifacts:
    paths:
      - .env.preprod
    expire_in: 1 hour
  only:
    - preprod
  tags:
    - docker

# ============================================
# Stage 2: Build - Construction de l'image Docker
# ============================================
build_image_preprod:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  needs:
    - generate_env_preprod
  script:
    - docker info
    - cp .env.preprod .env.production
    - docker build -t ${IMAGE_NAME}:preprod-${CI_COMMIT_SHORT_SHA} --target production .
    - docker tag ${IMAGE_NAME}:preprod-${CI_COMMIT_SHORT_SHA} ${IMAGE_NAME}:preprod-latest
    - docker save ${IMAGE_NAME}:preprod-${CI_COMMIT_SHORT_SHA} > image.tar
  artifacts:
    paths:
      - image.tar
      - .env.preprod
    expire_in: 1 hour
  only:
    - preprod
  tags:
    - docker

# ============================================
# Stage 3: Deploy - Déploiement en Pre-Production
# ============================================
deploy_preprod:
  stage: deploy
  image: alpine:3.20
  needs:
    - build_image_preprod
  before_script:
    - apk add --no-cache openssh-client docker-cli rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PREPROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_PREPROD" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      echo "Deploying to pre-production server..."

      # Transfert de l'image Docker
      scp -o StrictHostKeyChecking=no image.tar ${DEPLOY_USER_PREPROD}@${DEPLOY_HOST_PREPROD}:/tmp/helpdigischool-frontend.tar

      # Transfert des fichiers de configuration
      scp -o StrictHostKeyChecking=no .env.preprod ${DEPLOY_USER_PREPROD}@${DEPLOY_HOST_PREPROD}:/opt/helpdigischool/.env.preprod
      scp -o StrictHostKeyChecking=no docker-compose.preprod.yml ${DEPLOY_USER_PREPROD}@${DEPLOY_HOST_PREPROD}:/opt/helpdigischool/

      # Déploiement sur le serveur
      ssh -o StrictHostKeyChecking=no ${DEPLOY_USER_PREPROD}@${DEPLOY_HOST_PREPROD} << 'ENDSSH'
        cd /opt/helpdigischool

        # Charger l'image Docker
        docker load < /tmp/helpdigischool-frontend.tar

        # Arrêter l'ancien conteneur
        docker-compose -f docker-compose.preprod.yml down || true

        # Démarrer le nouveau conteneur
        docker-compose -f docker-compose.preprod.yml up -d

        # Nettoyer
        rm /tmp/helpdigischool-frontend.tar
        docker image prune -f

        # Vérifier le statut
        docker ps | grep helpdigischool
      ENDSSH

      echo "Deployment to pre-production completed!"
  environment:
    name: preprod
    url: https://preprod.helpdigischool.com
  only:
    - preprod
  tags:
    - docker
  when: manual

# ============================================
# Stage 4: Verify - Vérification du déploiement
# ============================================
verify_preprod:
  stage: deploy
  image: alpine:3.20
  needs:
    - deploy_preprod
  script:
    - apk add --no-cache curl
    - |
      echo "Waiting for service to be ready..."
      sleep 30

      echo "Checking health endpoint..."
      for i in $(seq 1 10); do
        if curl -sf https://preprod.helpdigischool.com/api/health; then
          echo "Health check passed!"
          exit 0
        fi
        echo "Attempt $i failed, retrying in 10s..."
        sleep 10
      done

      echo "Health check failed after 10 attempts"
      exit 1
  only:
    - preprod
  tags:
    - docker
  when: on_success