# ============================================
# Help Digi School - Frontend Next.js
# GitLab CI/CD - Pipeline Production
# ============================================

# ============================================
# Stage 1: Build - Génération du fichier .env
# ============================================
generate_env_prod:
  stage: build
  image: alpine:3.20
  script:
    - |
      cat > .env.production << EOF
      # ============================================
      # APPLICATION
      # ============================================
      NODE_ENV=production
      NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME_PROD:-Help Digi School}
      NEXT_PUBLIC_APP_URL=${HOST_URL_PROD}
      NEXT_PUBLIC_APP_DESCRIPTION=Plateforme de gestion scolaire
      NEXT_PUBLIC_ENVIRONMENT=production

      # ============================================
      # API - MICROSERVICES
      # ============================================
      NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL_PROD}
      NEXT_PUBLIC_API_TIMEOUT=30000

      # ============================================
      # DOCKER
      # ============================================
      FRONTEND_PORT=${PORT_PROD:-3000}
      VERSION=${CI_COMMIT_SHORT_SHA}

      # ============================================
      # AUTHENTIFICATION
      # ============================================
      NEXT_PUBLIC_SESSION_DURATION=3600

      # ============================================
      # FEATURES FLAGS
      # ============================================
      NEXT_PUBLIC_ENABLE_NOTIFICATIONS=true
      NEXT_PUBLIC_ENABLE_DARK_MODE=true
      NEXT_PUBLIC_ENABLE_ANALYTICS=true

      # ============================================
      # SENTRY (Monitoring erreurs)
      # ============================================
      # SENTRY_DSN=${SENTRY_DSN_PROD}
      # NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN_PROD}
      EOF
    - cat .env.production
  artifacts:
    paths:
      - .env.production
    expire_in: 1 hour
  only:
    - main
  tags:
    - docker

# ============================================
# Stage 2: Build - Construction de l'image Docker
# ============================================
build_image_prod:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  needs:
    - generate_env_prod
  script:
    - docker info
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} --target production .
    - docker tag ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} ${IMAGE_NAME}:latest
    - docker save ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} > image.tar
  artifacts:
    paths:
      - image.tar
      - .env.production
    expire_in: 1 hour
  only:
    - main
  tags:
    - docker

# ============================================
# Stage 3: Deploy - Déploiement en Production
# ============================================
deploy_prod:
  stage: deploy
  image: alpine:3.20
  needs:
    - build_image_prod
  before_script:
    - apk add --no-cache openssh-client docker-cli rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_PROD" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      echo "Deploying to production server..."

      # Transfert de l'image Docker
      scp -o StrictHostKeyChecking=no image.tar ${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD}:/tmp/helpdigischool-frontend.tar

      # Transfert des fichiers de configuration
      scp -o StrictHostKeyChecking=no .env.production ${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD}:/opt/helpdigischool/.env.production
      scp -o StrictHostKeyChecking=no docker-compose.prod.yml ${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD}:/opt/helpdigischool/

      # Déploiement sur le serveur
      ssh -o StrictHostKeyChecking=no ${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD} << 'ENDSSH'
        cd /opt/helpdigischool

        # Charger l'image Docker
        docker load < /tmp/helpdigischool-frontend.tar

        # Arrêter l'ancien conteneur (graceful)
        docker-compose -f docker-compose.prod.yml down || true

        # Démarrer le nouveau conteneur
        docker-compose -f docker-compose.prod.yml up -d

        # Nettoyer
        rm /tmp/helpdigischool-frontend.tar
        docker image prune -f

        # Vérifier le statut
        docker ps | grep helpdigischool
      ENDSSH

      echo "Deployment to production completed!"
  environment:
    name: production
    url: https://helpdigischool.com
  only:
    - main
  tags:
    - docker
  when: manual

# ============================================
# Stage 4: Verify - Vérification du déploiement
# ============================================
verify_prod:
  stage: deploy
  image: alpine:3.20
  needs:
    - deploy_prod
  script:
    - apk add --no-cache curl
    - |
      echo "Waiting for service to be ready..."
      sleep 30

      echo "Checking health endpoint..."
      for i in $(seq 1 10); do
        if curl -sf https://helpdigischool.com/api/health; then
          echo "Health check passed!"
          exit 0
        fi
        echo "Attempt $i failed, retrying in 10s..."
        sleep 10
      done

      echo "Health check failed after 10 attempts"
      exit 1
  only:
    - main
  tags:
    - docker
  when: on_success

# ============================================
# Rollback - En cas de problème
# ============================================
rollback_prod:
  stage: deploy
  image: alpine:3.20
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_PROD" >> ~/.ssh/known_hosts
  script:
    - |
      echo "Rolling back to previous version..."

      ssh -o StrictHostKeyChecking=no ${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD} << 'ENDSSH'
        cd /opt/helpdigischool

        # Récupérer la version précédente
        PREVIOUS_TAG=$(docker images ${IMAGE_NAME} --format "{{.Tag}}" | grep -v latest | head -2 | tail -1)

        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous version found!"
          exit 1
        fi

        echo "Rolling back to version: $PREVIOUS_TAG"

        # Modifier le tag dans le compose
        sed -i "s/:latest/:$PREVIOUS_TAG/g" docker-compose.prod.yml

        # Redémarrer avec l'ancienne version
        docker-compose -f docker-compose.prod.yml down
        docker-compose -f docker-compose.prod.yml up -d

        echo "Rollback completed!"
      ENDSSH
  environment:
    name: production
    url: https://helpdigischool.com
  only:
    - main
  tags:
    - docker
  when: manual