import {
  LayoutDashboard,
  Users,
  BookOpen,
  GraduationCap,
  FileText,
  CreditCard,
  Calendar,
  BarChart3,
  Bell,
  Settings,
  Building2,
  TrendingUp,
  Database,
  Shield,
  MessageSquare,
  Award,
  ClipboardList,
  User,
  Library,
  UserPlus,
  Phone,
  Printer,
} from 'lucide-react'
import { type MenuItem } from '@/components/dashboard/shared/Sidebar'

export const menuItemsByRole: Record<string, MenuItem[]> = {
  admin: [
    { icon: LayoutDashboard, label: "Vue d'ensemble", href: '/dashboard/admin' },
    { icon: Building2, label: 'Écoles', href: '/dashboard/admin/schools', badge: '127' },
    { icon: Users, label: 'Utilisateurs', href: '/dashboard/admin/users', badge: '2.4k' },
    { icon: CreditCard, label: 'Abonnements', href: '/dashboard/admin/subscriptions' },
    { icon: TrendingUp, label: 'Revenus', href: '/dashboard/admin/revenue' },
    { icon: BarChart3, label: 'Analytiques', href: '/dashboard/admin/analytics' },
    { icon: Database, label: 'Base de données', href: '/dashboard/admin/database' },
    { icon: Shield, label: 'Sécurité', href: '/dashboard/admin/security' },
    { icon: Settings, label: 'Paramètres', href: '/dashboard/admin/settings' },
  ],
  director: [
    { icon: LayoutDashboard, label: "Vue d'ensemble", href: '/dashboard/director' },
    { icon: Users, label: 'Élèves', href: '/dashboard/director/students', badge: '342' },
    { icon: BookOpen, label: 'Classes', href: '/dashboard/director/classes', badge: '12' },
    {
      icon: GraduationCap,
      label: 'Enseignants',
      href: '/dashboard/director/teachers',
      badge: '18',
    },
    { icon: FileText, label: 'Notes & Bulletins', href: '/dashboard/director/grades' },
    { icon: CreditCard, label: 'Paiements', href: '/dashboard/director/payments' },
    { icon: Calendar, label: 'Emploi du temps', href: '/dashboard/director/schedule' },
    { icon: BarChart3, label: 'Statistiques', href: '/dashboard/director/stats' },
    { icon: Bell, label: 'Notifications', href: '/dashboard/director/notifications', badge: '5' },
    { icon: Settings, label: 'Paramètres', href: '/dashboard/director/settings' },
  ],
  teacher: [
    { icon: LayoutDashboard, label: 'Tableau de bord', href: '/dashboard/teacher' },
    { icon: Users, label: 'Mes élèves', href: '/dashboard/teacher/students', badge: '32' },
    { icon: FileText, label: 'Saisie des notes', href: '/dashboard/teacher/grades' },
    { icon: BookOpen, label: 'Mes cours', href: '/dashboard/teacher/courses' },
    { icon: Calendar, label: 'Emploi du temps', href: '/dashboard/teacher/schedule' },
    { icon: ClipboardList, label: 'Présences', href: '/dashboard/teacher/attendance' },
    { icon: MessageSquare, label: 'Messages', href: '/dashboard/teacher/messages', badge: '3' },
    { icon: Award, label: 'Évaluations', href: '/dashboard/teacher/evaluations' },
    { icon: Settings, label: 'Paramètres', href: '/dashboard/teacher/settings' },
  ],
  student: [
    { icon: LayoutDashboard, label: 'Tableau de bord', href: '/dashboard/student' },
    { icon: Award, label: 'Mes Notes', href: '/dashboard/student/grades' },
    { icon: BookOpen, label: 'Mes Cours', href: '/dashboard/student/courses' },
    { icon: Calendar, label: 'Emploi du temps', href: '/dashboard/student/schedule' },
    { icon: FileText, label: 'Devoirs', href: '/dashboard/student/homework', badge: '3' },
    { icon: MessageSquare, label: 'Messages', href: '/dashboard/student/messages', badge: '2' },
    { icon: Library, label: 'Bibliothèque', href: '/dashboard/student/library' },
    { icon: Settings, label: 'Paramètres', href: '/dashboard/student/settings' },
  ],
  parent: [
    { icon: LayoutDashboard, label: 'Tableau de bord', href: '/dashboard/parent' },
    { icon: User, label: 'Mes enfants', href: '/dashboard/parent/children' },
    { icon: FileText, label: 'Bulletins', href: '/dashboard/parent/reports' },
    { icon: Award, label: 'Notes & Résultats', href: '/dashboard/parent/grades' },
    { icon: CreditCard, label: 'Paiements', href: '/dashboard/parent/payments' },
    { icon: Calendar, label: 'Emploi du temps', href: '/dashboard/parent/schedule' },
    { icon: MessageSquare, label: 'Messages', href: '/dashboard/parent/messages', badge: '2' },
  ],
  secretary: [
    { icon: LayoutDashboard, label: 'Tableau de bord', href: '/dashboard/secretary' },
    { icon: Users, label: 'Élèves', href: '/dashboard/secretary/students', badge: '342' },
    { icon: UserPlus, label: 'Inscriptions', href: '/dashboard/secretary/enrollments', badge: '5' },
    { icon: CreditCard, label: 'Paiements', href: '/dashboard/secretary/payments' },
    { icon: FileText, label: 'Documents', href: '/dashboard/secretary/documents' },
    { icon: Phone, label: 'Contacts', href: '/dashboard/secretary/contacts' },
    { icon: Calendar, label: 'Rendez-vous', href: '/dashboard/secretary/appointments', badge: '3' },
    { icon: Printer, label: 'Impressions', href: '/dashboard/secretary/printing' },
    { icon: Settings, label: 'Paramètres', href: '/dashboard/secretary/settings' },
  ],
}

export const roleDisplayInfo: Record<
  string,
  { userName: string; userRole: string; schoolName?: string }
> = {
  admin: { userName: 'Admin Principal', userRole: 'Super Admin', schoolName: 'Admin SaaS' },
  director: { userName: 'Jean Dupont', userRole: 'Directeur' },
  teacher: { userName: 'Marie Kouam', userRole: 'Enseignante CM2' },
  student: { userName: 'Amina Talla', userRole: 'Élève - CM2-A' },
  parent: { userName: 'Jean Talla', userRole: 'Parent' },
  secretary: { userName: 'Sophie Mballa', userRole: 'Secrétaire' },
}
